[package]
name = "download_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
chrono = { version = "0.4.41", features = ["serde"] }
reqwest = "0.12.15"
thiserror = "2.0.12"
uuid = { version = "1.16.0", features = ["v4"] }
url = "2.5.4"
