[package]
name = "download-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
net-manthan-core = { path = "../net-manthan-core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true