[package]
name = "native-message-host"
version = "0.1.0"
edition = "2021"

[dependencies]
net-manthan-core = { path = "../net-manthan-core" }
utils = { path = "../utils" }
serde.workspace = true
serde_json.workspace = true
chrome_native_messaging = "0.3.0"