[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
prost = "0.13.5"
tonic = "0.13.1"
prost-types = "0.13.5"

[build-dependencies]
tonic-build = "0.13.1"
