[application]

[web.app]

# HTML title tag content
title = "ui"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.netmanthan"
publisher = "NetManthan"

[build]
target = "x86_64-pc-windows-msvc"

[package.metadata.bundle]
windows = { winres = true }

[[bin]]
name = "net_manthan"
path = "src/main.rs"
test = false
bench = false
crate-type = ["bin"]