[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
download_engine = { path = "../download_engine" }
clap = { version = "4.5.27", features = ["derive"] }
tracing.workspace = true
tracing-subscriber.workspace = true
color-eyre = "0.6.3"