[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
download_engine = { path = "../download_engine" }
tracing.workspace = true
tracing-subscriber.workspace = true
color-eyre.workspace = true
clap = { version = "4.5.27", features = ["derive"] }