services:
  download-test-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./test_files:/usr/share/nginx/html/files
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  default:
    name: download-test-network
